---
abstract: 'Convert between various Chinese pinyin system and Indonesian transliteration'
author:
  - 'Steven Haryanto <stevenharyanto@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.300035, CPAN::Meta::Converter version 2.131560'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Lingua-ZH-PinyinConvert-ID
requires:
  perl: 5.010001
resources:
  homepage: http://search.cpan.org/dist/Lingua-ZH-PinyinConvert-ID/
  repository: http://github.com/sharyanto/perl-Lingua-ZH-PinyinConvert-ID
version: 0.04
